name: Backend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Archive build
      run:  tar -czf app.tar.gz package*.json dist .env --ignore-failed-read
      

    - name: Upload to EC2
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app.tar.gz"
        target: "~/backend-app"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/backend-app
          tar -xzf app.tar.gz && rm app.tar.gz

          # Optional: set env vars
          echo "${{ secrets.BACKEND_ENV_VARS }}" > .env

          # Install production dependencies
          npm ci --omit=dev

          # Restart app using PM2
          pm2 start npm --name backend-app -- start || pm2 restart backend-app
          pm2 save


          